### ISSUE TITLE
Leaderboard not always registering players

### ISSUE THREAD

**Issue by amberfoam** [fo-am/cricket-tales2#14]
I didn't appear on it!!

**Comment by nebogeo** [comment]
did the keyboard appear? you are registered but no name...

**Comment by nebogeo** [comment]
hmm bug - it'll probably ask you again next time...

**Comment by ThrasumaXus** [comment]
Same issue for me: none of my testing attempts (perhaps 10 sets of 5 clips) have been recorded on leaderboard (ID: PEH).

**Comment by nebogeo** [comment]
This should now be fixed (seems it was firefox), can someone check and close this issue if it works for you.
