### ISSUE TITLE
Description of cloudy day

### ISSUE THREAD

**Issue by Pleiotrope** [fo-am/cricket-tales2#21]
It is shady – the image is in colour but it’s a bit dark:

Maybe better to say: It is cloudy – the image is in colour but shadows aren't distinct – click the right button

**Comment by amberfoam** [comment]
I wonder if this info is actually useful - isn't day/night the thing that you're looking at? Should we reduce it to just two buttons maybe to avoid the ambiguity?

**Comment by Pleiotrope** [comment]
no, we are VERY interested in cloudy/sunny because we want to know if crickets move in and out of the sun as a method of thermoregulation.  We already know whether it's day or night from the time of day, but it's good to have the night option otherwise it will confuse people when it's night...
