### ISSUE TITLE
Third start prompt

### ISSUE THREAD

**Issue by ThrasumaXus** [fo-am/cricket-tales2#24]
It would be better to have a third 'prompt' before the video clip starts for weather because logging the weather can easily be missed when watching a run of videos.

**Comment by nebogeo** [comment]
I know what you mean, but my feeling on this is that there is enough to do already without interrupting the flow even more... I think the toggling behaviour helps with this issue too...

**Comment by ThrasumaXus** [comment]
Yes, I've tried it this morning and the 'toggle'(?) buttons are a real improvement. At present, at least on Safari, the last toggled button remains 'lit' during and after the transitions through the five clips in each batch of five. These buttons should really reset for each clip I think. 
The clarity and simplicity of this highlighted button approach reinforces my view that the singing and feeding buttons should toggle in the same way (possibly being labelled 'sang' and 'fed' to avoid the feeling that there ought to be a toggle-off).

**Comment by nebogeo** [comment]
I've fixed that bug. The problem with toggling singing/feeding is that as the cricket is often not doing either and feels like it's wrong to have one highlighted. If it does both you'd need both on - so it all goes wrong. I've made the sing/feeding light up for 5 seconds which feels about right to indicate that you don't need to repeatedly hit the button, or worry about when the behaviour ends.

**Comment by ThrasumaXus** [comment]
Yes that seems to work. Does it register multiple hits if they occur, or just one per clip?

**Comment by nebogeo** [comment]
It records every click - but it's a simple matter to filter these out later on, and just look for the videos with 1 or more singing events associated etc.

**Comment by ThrasumaXus** [comment]
Hi Dave and Amber,


Cricket tales is looking great and seems to be smooth and almost glitch free - I love the cartoon crickets with gently twitching antennae.


I'm sorry, at this stage we've thought of a couple of additional points related to the datasheet (hopefully small) that are important: we need an identifier of the video clip and the duration of the clip in real time.


Also may we ask for clarification for one or two outstanding queries before we meet up please? (Some you may have already answered so apologies if so).


These are:


1) Does the 'Time' data field indicate the time stamped on the video? If so what are last 6 digits in the Time field?


2) Does the first click mark the real time when the video clip starts?


3) We have the list of event types (on the spreadsheet you sent) but there is an additional event type called “video” that was not in the list. Other than that we think we're clear what all the events are. May we precis our understanding of what all the events are and get you to check we've not misunderstood anything important please?!



4) Our understanding is that the usefulness of the “frame” field in the data file you sent is to get a relative frame position within each video file (each of which is always 300 frames long). However the “frame” numbers in the spreadsheet are quite high and vary a lot: Is the starting frame value always the start of the day and if not how are the frame numbers obtained?


5) using percentages for the coordinates is a good idea to account for differences in the size and resolution of users' screens. However, in the spreadsheet that you sent, 63% of the records have coordinates 0,0, so there must be a problem. This is how the zero's are distributed across event types:



Event type


N at 0,0


eating


24


in


73


mid


164


night


11


no_cricket_end


23


no_cricket_start


41


out


174


shade


59


singing


74


sun


80


video


14


video_restart


10





Thanks again!


Paul





________________________________

**Comment by ThrasumaXus** [comment]
Hi Paul,

On 06/12/18 12:17, Hopwood, Paul wrote:
> I'm sorry, at this stage we've thought of a couple of additional
> points related to the datasheet (hopefully small) that are
> important: *w**e need an identifier of the video clip and the duration
> of the clip in real time.*

This is in already: "Movie ID" is a unique code for the clip, and
instead of duration you have "Movie start time" and "Movie end time"
which are in real time:

http://cricket-tales.ex.ac.uk/media/data/events.csv

(that file is auto-generated every midnight so should always be up to date)

> Also may we ask for clarification for one or two outstanding queries
> before we meet up please? (Some you may have already answered so
> apologies if so).

No problem.

> 1) Does the 'Time' data field indicate the time stamped on the video? If
> so what are last 6 digits in the Time field?

Yes it's the real time of the event from the frame information in the
source data. The date format - e.g.:

2013-05-24 14:17:10+00:00

Is a standard format so includes the offset from UTC at the end (+00:00)
- which we don't use so you can ignore it (well, it's always zero).

> 2) Does the first click mark the real time when the video clip starts?

Yes, you are right, so it's probably redundant, but reassuring.

> 3) We have the list of event types (on the spreadsheet you sent) but
> there is an additional event type called “*video*” that was not in the
> list. Other than that we think we're clear what all the events are. May
> we precis our understanding of what all the events are and get you to
> check we've not misunderstood anything important please?!

Ahah "video" is a bug! When you click on the video while it's playing at
any time - and it sends an event called video with those coordinates! I
just removed that :)

Yes I'm happy to go over these with you. It's important we get it right!

> 4) Our understanding is that the usefulness of the “frame” field in the
> data file you sent is to get a relative frame position within each video
> file (each of which is always 300 frames long). However the “frame”
> numbers in the spreadsheet are quite high and vary a lot: Is the
> starting frame value always the start of the day and if not how are the
> frame numbers obtained?

Yes this frame is the corresponding frame in the index file (so the
watched video frame number (0-300) + the "start frame" of that clip) so
probably not of much use to you - but it means we can double check the
time information by looking at that specific frame.

> *5) *using percentages for the coordinates is a good idea to account for
> differences in the size and resolution of users' screens. However, in
> the spreadsheet that you sent, 63% of the records have coordinates 0,0,
> so there must be a problem. This is how the zero's are distributed
> across event types:

Most of them are 0,0 as they record a button click rather than clicking
on the video.

Hope that makes sense!

cheers,

dave
