### ISSUE TITLE
Button click indicator and 'hold' required

### ISSUE THREAD

**Issue by ThrasumaXus** [fo-am/cricket-tales2#25]
Each button should change colour and become inactive to show that it was the last state in that group to be recorded/clicked (e.g. 'in burrow' is clicked and button becomes inactive until 'half in' or 'outside' is clicked). This will indicate which was the last status recorded and remind user to click weather etc when things change during each video clip.

**Comment by nebogeo** [comment]
This makes sense, so each row of buttons is a group - and acts like a 'radio' button in behaviour...

**Comment by nebogeo** [comment]
This works for sun/shade/night and in/mid/out but for singing and eating, you feel like you need to turn them off when they stop. We could do this with another click - but it means recording it differently in the database - eating-start/eating-end and singing-start and singing-end. Is that ok?

**Comment by ThrasumaXus** [comment]
Good point. However, I think for sampling purposes it is sufficient to record that an individual sang or fed at some point during that particular time period (when it was either sunny, cloudy or night). I.e., it's not a 'duration', it's a 'did they do it'? Perhaps the button label might be 'seen eating' and 'seen singing'  to clarify this. Then the button could remain 'on' when pressed once?
