### ISSUE TITLE
Shrews and birds

### ISSUE THREAD

**Issue by ThrasumaXus** [fo-am/cricket-tales2#26]
There ought to be a note to look out for, and expect the unexpected, for example, shrews or birds or other animals visiting - but that these don't need to be logged.

**Comment by nebogeo** [comment]
If they don't need to be logged then there is no need to mention them - we need to reduce text to an absolute minimum.

**Comment by ThrasumaXus** [comment]
Fair enough, yes they don't need to be logged and these unexpected events (attacks or visits by shrews / birds / snakes / lizards etc.) are relatively uncommon. It's just whether it would be useful to reassure users that any such arresting events can be ignored.

**Comment by nebogeo** [comment]
This is a similar problem to #13 - I think we just leave these kinds of surprises for people to find. Either that or put the unexpected event exclamation mark button back in - but not record anything when it's clicked on :) (not really)

**Comment by nebogeo** [comment]
I think it's fine to have interesting things happen that we are obviously not needing to record - all that stuff is part of what makes it fun.
